spring.application.name=app-service
spring.profiles.active=dev

## Google Maps API Key
google.maps.api.key=${GOOGLE_MAPS_API_KEY}

## JWT Configuration
jwt.secret=federicomartinfunespalaciodailanahirjuarezbebede
jwt.expiration=3600000
