spring.application.name=app-service
spring.profiles.active=dev

## Google Maps API Key
google.maps.api.key=${GOOGLE_MAPS_API_KEY}

## JWT Configuration
jwt.secret=federicomartinfunespalaciodailanahirjuarezbebede
jwt.expiration=3600000

## Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=federicomartinfp@gmail.com
spring.mail.password=dauc gust rdgm griu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

